Chapter04-Ruby_on_Rails/odin-facebook/config/routes.rb
Rails.application.routes.draw do

  get 'friends/index'
  get 'friends/destroy'
  get '/posts', to: redirect('/')
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :comments
  resources :friend_requests, only: [:index, :create, :destroy, :update]
  resources :posts, only: [:create, :destroy]
  resources :users, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  root 'static_pages#home'
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/friend_request.rb
class FriendRequest < ApplicationRecord

	validates :user_id, presence: true
	validates :friend_id, presence: true
	validate :not_self
	validate :not_friends
  validate :not_pending

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  # This method will build the actual association and destroy the request
	def accept
		user.friends << friend
		destroy
	end

  private

		def not_self
		  errors.add(:friend, "can't be equal to user") if user == friend
		end

		def not_friends
    	errors.add(:friend, 'is already added') if user.friends.include?(friend)
 		 end

  	def not_pending
    	errors.add(:friend, 'already requested friendship') if user.pending_friends.include?(friend)
  	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/friendship.rb
class Friendship < ApplicationRecord
	after_create :create_inverse_relationship
	after_destroy :destroy_inverse_relationship
	validates :user, presence: true
	validates :friend, presence: true, uniqueness: { scope: :user }
	validate :not_self

	belongs_to :user
	belongs_to :friend, class_name: 'User'

	private

	def create_inverse_relationship

		friend.friendships.create(friend: user)
	end

	def destroy_inverse_relationship
		friendship = friend.friendships.find_by(friend: user)
		friendship.destroy if friendship
	end

	def not_self
  	errors.add(:friend, "can't be equal to user") if user == friend
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/post.rb
class Post < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 200 }
	belongs_to :user
	has_many :likes
	has_many :liking_users, :through => :likes, :source => :user
	has_many :comments
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]
  validates :name, presence: true, length: { maximum: 50 }
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post
  has_many :comments

  def remove_friend(friend)
  	friends.destroy(friend)
  end

  def friend?(user)
    friends.include?(user)
  end

  def pending_friend?(user)
    pending_friends.include?(user)
  end

  def feed
    friend_ids = "SELECT friend_id FROM friendships
                  WHERE user_id = :user_id"
    Post.where("user_id IN (#{friend_ids}) 
              OR user_id = :user_id", user_id: id)
  end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@post = Post.find(params[:comment][:post_id])
		@comment = @post.comments.build(comment_params)
		if @comment.save
			redirect_to request.referrer || root_url
		else
			flash[:danger] = "Comment error"
			redirect_to request.referrer || root_url
		end

	end

	def destroy
	end

	private
		def comment_params
			params.require(:comment).permit(:body, :user_id)
		end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :set_friend, only: :destroy

  def index
  	@friends = current_user.friends
  end

  def destroy
  	current_user.remove_friend(@friend)
    flash[:danger] = "Friend removed!"
    redirect_to request.referrer || root_url
  end

  private

  	def set_friend
  		@friend = current_user.friends.find(params[:id])
  	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def create
		like = Like.new(user_id: params[:user_id], post_id: params[:post_id])
		if like.save
			redirect_to request.referrer || root_url
		end

	end

	def destroy
		@like = Like.find(params[:id])
		@like.destroy
		redirect_to request.referrer || root_url
	end

end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post Created!"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	private

		def post_params
			params.require(:post).permit(:content)
		end

		def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page])
		@comment = Comment.new
		@friends = current_user.friends
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Odin-Facebook"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/comments_helper.rb
module CommentsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/friends_helper.rb
module FriendsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/likes_helper.rb
module LikesHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/posts_helper.rb
module PostsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Odin-Facebook", root_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_url %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to current_user.name.capitalize, user_path(current_user) %></li>
          <li><%= link_to "Friends", friends_index_path %></li>
          <li><%= link_to "Notifications", friend_requests_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/shared/_comment_form.html.erb
<%= form_for(@comment, url: comments_path) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.hidden_field(:post_id, value: post.id) %>
	<%= f.hidden_field(:user_id, value: current_user.id) %>
  <div class="field">
    <%= f.text_area :body, placeholder: "New comment..." %>
  </div>
  <%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>