Chapter04-Ruby_on_Rails/odin-facebook/config/routes.rb
Rails.application.routes.draw do

  get 'friends/index'
  get 'friends/destroy'
  get '/posts', to: redirect('/')
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :comments
  resources :friend_requests, only: [:index, :create, :destroy, :update]
  resources :posts, only: [:create, :destroy]
  resources :users, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  root 'static_pages#home'
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/friend_request.rb
class FriendRequest < ApplicationRecord

	validates :user_id, presence: true
	validates :friend_id, presence: true
	validate :not_self
	validate :not_friends
  validate :not_pending

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  # This method will build the actual association and destroy the request
	def accept
		user.friends << friend
		destroy
	end

  private

		def not_self
		  errors.add(:friend, "can't be equal to user") if user == friend
		end

		def not_friends
    	errors.add(:friend, 'is already added') if user.friends.include?(friend)
 		 end

  	def not_pending
    	errors.add(:friend, 'already requested friendship') if user.pending_friends.include?(friend)
  	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_friend_request, except: [:index, :create]

	def create
		@user = User.find(params[:friend_id])
		@friend_request = current_user.friend_requests.new(friend: @user)

		if @friend_request.save
			flash[:success] = "Friend Request Sended!"
		else
			flash[:danger] = "Invalid Request"
		end
		redirect_to request.referrer || root_url
		respond_to do |format|
			format.html { redirect_to current_user }
			format.js
		end
	end

	def index
		@incoming = FriendRequest.where(friend: current_user)
		@outgoing = current_user.friend_requests
	end

	def update
		@friend_request.accept
		flash[:success] = "New friend added!"
		redirect_to friend_requests_path
	end

	def destroy
		@user = @friend_request.friend
		@friend_request.destroy
		flash[:danger] = "Friend request eliminated!"
		redirect_to request.referrer || root_url
		respond_to do |format|
			format.html { redirect_to current_user }
			format.js
		end
	end

	private

		def set_friend_request
			@friend_request = FriendRequest.find(params[:id])
		end

end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/views/friend_requests/create.js.erb
$("#friend_request_form").html("<%= escape_javascript(render('users/remove_friend_request')) %>");

Chapter04-Ruby_on_Rails/odin-facebook/app/views/friend_requests/destroy.js.erb
$("#friend_request_form").html("<%= escape_javascript(render('users/add_friend')) %>");

Chapter04-Ruby_on_Rails/odin-facebook/app/views/friend_requests/index.html.erb
<h1><%= current_user.name.capitalize %> Notifications</h1>
<h2>Friend Requests</h2>
<ul>
	<% @incoming.each do |request| %>
		<li><%= request.user.name.capitalize %></li>
		<%= link_to "Confirm", friend_request_path(request), method: :patch %>
		<%= link_to "Eliminate", friend_request_path(request), method: :delete %>
	<% end %>
</ul>
<h2>Pending Friends</h2>
<ul>
	<% @outgoing.each do |request| %>
		<li><%= request.friend.name.capitalize %></li>
	<% end %>
</ul>