Chapter04-Ruby_on_Rails/odin-facebook/config/routes.rb
Rails.application.routes.draw do

  get 'friends/index'
  get 'friends/destroy'
  get '/posts', to: redirect('/')
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :comments
  resources :friend_requests, only: [:index, :create, :destroy, :update]
  resources :posts, only: [:create, :destroy]
  resources :users, only: [:index, :show]
  resources :likes, only: [:create, :destroy]
  root 'static_pages#home'
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/friend_request.rb
class FriendRequest < ApplicationRecord

	validates :user_id, presence: true
	validates :friend_id, presence: true
	validate :not_self
	validate :not_friends
  validate :not_pending

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  # This method will build the actual association and destroy the request
	def accept
		user.friends << friend
		destroy
	end

  private

		def not_self
		  errors.add(:friend, "can't be equal to user") if user == friend
		end

		def not_friends
    	errors.add(:friend, 'is already added') if user.friends.include?(friend)
 		 end

  	def not_pending
    	errors.add(:friend, 'already requested friendship') if user.pending_friends.include?(friend)
  	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/friendship.rb
class Friendship < ApplicationRecord
	after_create :create_inverse_relationship
	after_destroy :destroy_inverse_relationship
	validates :user, presence: true
	validates :friend, presence: true, uniqueness: { scope: :user }
	validate :not_self

	belongs_to :user
	belongs_to :friend, class_name: 'User'

	private

	def create_inverse_relationship

		friend.friendships.create(friend: user)
	end

	def destroy_inverse_relationship
		friendship = friend.friendships.find_by(friend: user)
		friendship.destroy if friendship
	end

	def not_self
  	errors.add(:friend, "can't be equal to user") if user == friend
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/post.rb
class Post < ApplicationRecord
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :content, presence: true, length: { maximum: 200 }
	belongs_to :user
	has_many :likes
	has_many :liking_users, :through => :likes, :source => :user
	has_many :comments
end

Chapter04-Ruby_on_Rails/odin-facebook/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]
  validates :name, presence: true, length: { maximum: 50 }
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_posts, :through => :likes, :source => :post
  has_many :comments

  def remove_friend(friend)
  	friends.destroy(friend)
  end

  def friend?(user)
    friends.include?(user)
  end

  def pending_friend?(user)
    pending_friends.include?(user)
  end

  def feed
    friend_ids = "SELECT friend_id FROM friendships
                  WHERE user_id = :user_id"
    Post.where("user_id IN (#{friend_ids}) 
              OR user_id = :user_id", user_id: id)
  end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@post = Post.find(params[:comment][:post_id])
		@comment = @post.comments.build(comment_params)
		if @comment.save
			redirect_to request.referrer || root_url
		else
			flash[:danger] = "Comment error"
			redirect_to request.referrer || root_url
		end

	end

	def destroy
	end

	private
		def comment_params
			params.require(:comment).permit(:body, :user_id)
		end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :set_friend, only: :destroy

  def index
  	@friends = current_user.friends
  end

  def destroy
  	current_user.remove_friend(@friend)
    flash[:danger] = "Friend removed!"
    redirect_to request.referrer || root_url
  end

  private

  	def set_friend
  		@friend = current_user.friends.find(params[:id])
  	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def create
		like = Like.new(user_id: params[:user_id], post_id: params[:post_id])
		if like.save
			redirect_to request.referrer || root_url
		end

	end

	def destroy
		@like = Like.find(params[:id])
		@like.destroy
		redirect_to request.referrer || root_url
	end

end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post Created!"
			redirect_to root_url
		else
			@feed_items = []
			render 'static_pages/home'
		end
	end

	def destroy
		@post.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	private

		def post_params
			params.require(:post).permit(:content)
		end

		def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/registrations_controller.rb
# Include name
class RegistrationsController < Devise::RegistrationsController

	def create
		super
		#UserMailer.welcome_email(resource).deliver_now unless resource.invalid?
	end

	private

		def sign_up_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		def account_update_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
		end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
		if user_signed_in?
			@user = current_user
			@post = current_user.posts.build
			@feed_items = current_user.feed.paginate(page: params[:page])
			@comment = Comment.new
		end
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.paginate(page: params[:page])
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.paginate(page: params[:page])
		@comment = Comment.new
		@friends = current_user.friends
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Odin-Facebook"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/comments_helper.rb
module CommentsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/friends_helper.rb
module FriendsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/likes_helper.rb
module LikesHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/posts_helper.rb
module PostsHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Chapter04-Ruby_on_Rails/odin-facebook/app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

Chapter04-Ruby_on_Rails/odin-facebook/app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
	<%= link_to gravatar_for(post.user, size: 50), post.user %>
	<span class="user"><%= link_to post.user.name.capitalize, post.user %></span>
	<span class="content"><%= post.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(post.created_at) %> ago.</span>
	<% if current_user.liked_posts.include?(post) %>
		<%= link_to "Unlike", like_path(post.likes.where(user_id: current_user.id).take), method: :delete %>
	<% else %>
		<%= link_to "Like", likes_path(:user_id => current_user.id, :post_id => post.id), method: :post %>
	<% end %>

	<% if current_user == post.user %>
		<%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
	<div class="comment_form">
		<%= render 'shared/comment_form', post: post %>
	</div>
	<div class="comment_list">
		<% if post.comments.size >= 1 %>
			<ul>
				<% post.comments.each do |comment| %>
					<li><%= link_to comment.user.name.capitalize, comment.user %>: <%= comment.body %></li>
				<% end %>
			</ul>
		<% end %>
	</div>
</li>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/users/_add_friend.html.erb
<%= form_for(current_user.friend_requests.build, remote: true) do |f| %>
	<div><%= hidden_field_tag :friend_id, @user.id %></div>
	<%= f.submit "Add Friend", class: "btn btn-primary" %>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/users/_friend_request_form.html.erb
<% unless current_user == @user %>
	<div id="friend_request_form">
	<% if current_user.pending_friend?(@user) %>
		<%= render 'remove_friend_request' %>
	<% elsif @friends.include?(@user) %>
		<%= render 'remove_friend' %>
	<% else %>
		<%= render 'add_friend' %>
	<% end %>
	</div>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/users/_remove_friend.html.erb
<%= form_tag({controller: "friends", action: "destroy"}, method: "get") do %>
	<%= hidden_field_tag :id, @user.id %>
	<%=  submit_tag "Remove Friend", class: "btn" %>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/users/_remove_friend_request.html.erb
<%= form_for(current_user.friend_requests.find_by(friend_id: @user.id),
	           html: { method: :delete },
	           remote: true) do |f| %>
	<%= f.submit "Remove Friend Request", class: "btn" %>
<% end %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<li>
			<%= gravatar_for user, size: 50 %>
			<%= link_to user.name, user %>
		</li>
	<% end %>
</ul>

<%= will_paginate %>

Chapter04-Ruby_on_Rails/odin-facebook/app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name.capitalize %> Page</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'friend_request_form' if user_signed_in? %>
	</div>
</div>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      	<%= gravatar_for @user %>
        <%= @user.name.capitalize %>
      </h1>
    </section>
  </aside>
	<div class="col-md-8">
		<% if @user.posts.any? %>
			<h3>Posts</h3>
			<ol class="posts">
				<%= render @posts %>
			</ol>
			<%= will_paginate @posts %>
		<% end %>
	</div>
</div>	